name: build-and-deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE: raedbari/node.js
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.TAG }}

  deploy_to_kubernetes:
    needs: build_and_push
    runs-on: self-hosted
    env:
      IMAGE: raedbari/node.js
      TAG: ${{ github.sha }}
      NAMESPACE: project-env
      DEPLOYMENT: project-dep
      CONTAINER: nodejs
    steps:
      - name: Update Deployment image and rollout
        run: |
          kubectl -n "$NAMESPACE" set image deployment/"$DEPLOYMENT" \
            "$CONTAINER"=${IMAGE}:${TAG}
          kubectl -n "$NAMESPACE" rollout status deployment/"$DEPLOYMENT" --timeout=180s
          kubectl -n "$NAMESPACE" get deploy "$DEPLOYMENT" -o=jsonpath='{.spec.template.spec.containers[0].image}'; echo
